apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  labels:
    app: myapp
    slot: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      slot: green
  template:
    metadata:
      labels:
        app: myapp
        slot: green
        version: v2
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          command: ["/bin/sh", "-c"]
          args:
            - echo "<h1>MyApp</h1><p>GREEN ENVIRONMENT</p>" > /usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'
          ports:
            - containerPort: 80
