apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-recreate
  labels:
    app: app-recreate
spec:
  replicas: 3
  strategy:
    type: Recreate      # kill ALL old pods before creating any new ones
  selector:
    matchLabels:
      app: app-recreate
  template:
    metadata:
      labels:
        app: app-recreate
        version: v2
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "VERSION: v2 (UPGRADED)" > /usr/share/nginx/html/index.html
              exec nginx -g 'daemon off;'
          ports:
            - containerPort: 80
